spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 899125363767-v5c5ls5b2a9969gcnlgc0vdira7065k2.apps.googleusercontent.com
            client-secret: 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

server:
  port: 8080
