package com.example.demo3.User.Wallet;

import com.example.demo3.User.BBuser;
import jakarta.persistence.*;

@Entity
@Table(name = "wallet")
public class Wallet {
    /* WALLET TABLE IN DATABASE
       ID  : generated by db
       UID : linked from user
       BALANCE
   *  when every user is created , it should create a wallet for the user :
   thus alter the addNewUserMethods as well
   *
   * */

    @Id
    @SequenceGenerator(
            name = "wallet_sequence",
            sequenceName = "wallet_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "wallet_sequence"
    )
    private long id;

    public BBuser getBbuser() {
        return bbuser;
    }

    public void setBbuser(BBuser bbuser) {
        this.bbuser = bbuser;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private BBuser bbuser;

    private double balance;

    public Wallet() {
    }
    public Wallet(double balance){
        this.balance = balance;
    }


    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public double getBalance() {
        return balance;
    }

    public void setBalance(double balance) {
        this.balance = balance;
    }

}
