package com.example.demo3.User.Wallet;

import jakarta.persistence.*;

@Entity
@Table(name = "wallet")
public class Wallet {
    /* WALLET TABLE IN DATABASE
       ID  : generated by db
       UID : linked from user
       BALANCE
   *  when every user is created , it should create a wallet for the user :
   thus alter the addNewUserMethods as well
   *
   * */

    @Id
    @SequenceGenerator(
            name = "wallet_sequence",
            sequenceName = "wallet_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "wallet_sequence"
    )
    private long id;
    private long uid;
    private double balance;

    public Wallet() {
    }
    public Wallet(double balance){
        this.balance = balance;
    }



}
